Major update from UPV
5G-MAG/rt-wui pull request #13
Opened 2024-10-01 12:33 UTC by jsroldan

Added new dinamic graph for BLER and SNR.
Added control pannel to modify the receiver parameters. Added brief description to options and values.

2024-10-08 09:31 UTC, dsilhavy commented
@alessandro-lucco: Fyi, this PR includes the changes presented by @jsroldan in the last call. If you find the time, it would be nice if you can run some tests on your side as well. We are currently testing against sample recordings: https://5g-mag.github.io/Getting-Started/pages/lte-based-5g-broadcast/additional/sample-files.html

2024-10-29 07:52 UTC, dsilhavy requested changes

2024-10-29 07:52 UTC, dsilhavy commented on package-lock.json
> +  "version": "0.1.1",
Increase version number to `0.2.0` in package.json and run `npm install` again. This should update the `package-lock.json` as well.

2024-10-29 07:52 UTC, dsilhavy commented on app/assets/js/modem.js
> +  //canvas.width = canvas.parentElement.clientWidth;
Remove commented lines

2024-10-29 07:52 UTC, dsilhavy commented on app/assets/js/modem.js
> +  //  ctx.clearRect( 0, 0, canvas.width, canvas.height );
Remove commented lines

2024-10-29 07:52 UTC, dsilhavy commented on app/assets/js/modem.js
> +      //ctx.moveTo(0, y);
Remove commented lines

2024-10-29 07:52 UTC, dsilhavy commented on app/assets/js/modem.js
> +      //ctx.stroke();
Remove commented lines

2024-10-29 07:52 UTC, dsilhavy commented on app/assets/js/modem.js
> +/*  ctx.globalCompositeOperation = "copy";
Remove commented lines

2024-10-29 07:52 UTC, dsilhavy commented on app/assets/js/modem.js
> +
Remove empty lines

2024-10-29 07:52 UTC, dsilhavy commented on app/assets/js/modem.js
> +        //clear_all();
Remove commented lines

2024-10-29 07:52 UTC, dsilhavy commented on app/assets/js/modem.js
> +
Remove empty lines

2024-10-29 07:52 UTC, dsilhavy commented on app/controllers/api/modem.js
> +
Remove empty lines

2024-10-29 07:52 UTC, dsilhavy commented on app/routes.js
> +
Remove empty lines

2024-10-29 07:52 UTC, dsilhavy commented on app/views/layouts/application.ejs
> +    <!--div class="container"><!-->
Remove commented lines

2025-08-08 12:34 UTC, jordijoangimenez approved these changes

2025-08-08 12:35 UTC, merged